# PROYECTO FINAL PYTHON INICIAL 
# AUTOR: FRANCO BALTASAR MASSI
# BUSCADOR DE ALQUILERES
    
def main():
    #Funcion principal del programa. 
    print("BIENVENIDO AL BUSCADOR DE ALQUILERES")
    print("AQUI USTED PODRA ENCONTRAR LOS MEJORES DEPARTAMENTOS EN ALQUILER EN LA CIUDAD \nDE MENDOZA, CON LAS CARACTERISTICAS QUE USTED DESEE.")
    #
main()

